default: &default
  adapter: postgresql
  encoding: unicode
  username: 'neznauy'
  password: 'qwerty'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
  <<: *default
  database: db_production